/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Category = IDL.Variant({
  'Meat' : IDL.Null,
  'Beverages' : IDL.Null,
  'Dairy' : IDL.Null,
  'Bakery' : IDL.Null,
  'Household' : IDL.Null,
  'PersonalCare' : IDL.Null,
  'Vegetables' : IDL.Null,
  'Snacks' : IDL.Null,
  'Fruits' : IDL.Null,
});
export const CreateProductRequest = IDL.Record({
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'imageId' : IDL.Text,
  'price' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : Category,
  'imageId' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'InTransit' : IDL.Null,
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
});
export const Address = IDL.Record({
  'tag' : IDL.Text,
  'city' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserId = IDL.Principal;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderView = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'deliveryFee' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'estimatedDelivery' : Timestamp,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const CartItemView = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'savedAddresses' : IDL.Vec(Address),
  'email' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const PlaceOrderRequest = IDL.Record({ 'deliveryAddress' : Address });
export const UpdateProfileRequest = IDL.Record({
  'name' : IDL.Text,
  'savedAddresses' : IDL.Vec(Address),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func([CreateProductRequest], [Product], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItemView)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderView)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [OrderView], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'setAdminStatus' : IDL.Func([UserId, IDL.Bool], [], []),
  'updateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus],
      [IDL.Opt(OrderView)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, CreateProductRequest],
      [IDL.Opt(Product)],
      [],
    ),
  'updateProfile' : IDL.Func([UpdateProfileRequest], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Category = IDL.Variant({
    'Meat' : IDL.Null,
    'Beverages' : IDL.Null,
    'Dairy' : IDL.Null,
    'Bakery' : IDL.Null,
    'Household' : IDL.Null,
    'PersonalCare' : IDL.Null,
    'Vegetables' : IDL.Null,
    'Snacks' : IDL.Null,
    'Fruits' : IDL.Null,
  });
  const CreateProductRequest = IDL.Record({
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'imageId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : Category,
    'imageId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'InTransit' : IDL.Null,
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
  });
  const Address = IDL.Record({
    'tag' : IDL.Text,
    'city' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderView = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : Address,
    'deliveryFee' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'estimatedDelivery' : Timestamp,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const CartItemView = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'savedAddresses' : IDL.Vec(Address),
    'email' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const PlaceOrderRequest = IDL.Record({ 'deliveryAddress' : Address });
  const UpdateProfileRequest = IDL.Record({
    'name' : IDL.Text,
    'savedAddresses' : IDL.Vec(Address),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func([CreateProductRequest], [Product], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItemView)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderView)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [OrderView], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'setAdminStatus' : IDL.Func([UserId, IDL.Bool], [], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(OrderView)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, CreateProductRequest],
        [IDL.Opt(Product)],
        [],
      ),
    'updateProfile' : IDL.Func([UpdateProfileRequest], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };