/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'tag' : string,
  'city' : string,
  'line1' : string,
  'line2' : string,
  'pincode' : string,
}
export interface CartItemView { 'productId' : ProductId, 'quantity' : bigint }
export type Category = { 'Meat' : null } |
  { 'Beverages' : null } |
  { 'Dairy' : null } |
  { 'Bakery' : null } |
  { 'Household' : null } |
  { 'PersonalCare' : null } |
  { 'Vegetables' : null } |
  { 'Snacks' : null } |
  { 'Fruits' : null };
export interface CreateProductRequest {
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : Category,
  'imageId' : string,
  'price' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'InTransit' : null } |
  { 'Delivered' : null } |
  { 'Confirmed' : null };
export interface OrderView {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'deliveryFee' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'estimatedDelivery' : Timestamp,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface PlaceOrderRequest { 'deliveryAddress' : Address }
export interface Product {
  'id' : ProductId,
  'inStock' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : Category,
  'imageId' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export interface UpdateProfileRequest {
  'name' : string,
  'savedAddresses' : Array<Address>,
  'email' : string,
  'phone' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'savedAddresses' : Array<Address>,
  'email' : string,
  'isAdmin' : boolean,
  'phone' : string,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<[CreateProductRequest], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAllOrders' : ActorMethod<[], Array<OrderView>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItemView>>,
  'getMyOrders' : ActorMethod<[], Array<OrderView>>,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderView]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], OrderView>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedProducts' : ActorMethod<[], undefined>,
  'setAdminStatus' : ActorMethod<[UserId, boolean], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [OrderView]>,
  'updateProduct' : ActorMethod<
    [ProductId, CreateProductRequest],
    [] | [Product]
  >,
  'updateProfile' : ActorMethod<[UpdateProfileRequest], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];