/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaceOrderRequest {
    deliveryAddress: Address;
}
export type Timestamp = bigint;
export interface UserProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    savedAddresses: Array<Address>;
    email: string;
    isAdmin: boolean;
    phone: string;
}
export interface Product {
    id: ProductId;
    inStock: boolean;
    name: string;
    createdAt: Timestamp;
    description: string;
    category: Category;
    imageId: string;
    price: bigint;
}
export interface Address {
    tag: string;
    city: string;
    line1: string;
    line2: string;
    pincode: string;
}
export interface OrderItem {
    name: string;
    productId: ProductId;
    quantity: bigint;
    price: bigint;
}
export type UserId = Principal;
export interface UpdateProfileRequest {
    name: string;
    savedAddresses: Array<Address>;
    email: string;
    phone: string;
}
export interface CreateProductRequest {
    inStock: boolean;
    name: string;
    description: string;
    category: Category;
    imageId: string;
    price: bigint;
}
export interface CartItemView {
    productId: ProductId;
    quantity: bigint;
}
export type ProductId = bigint;
export type OrderId = bigint;
export interface OrderView {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: Address;
    deliveryFee: bigint;
    userId: UserId;
    createdAt: Timestamp;
    estimatedDelivery: Timestamp;
    totalAmount: bigint;
    items: Array<OrderItem>;
}
export enum Category {
    Meat = "Meat",
    Beverages = "Beverages",
    Dairy = "Dairy",
    Bakery = "Bakery",
    Household = "Household",
    PersonalCare = "PersonalCare",
    Vegetables = "Vegetables",
    Snacks = "Snacks",
    Fruits = "Fruits"
}
export enum OrderStatus {
    InTransit = "InTransit",
    Delivered = "Delivered",
    Confirmed = "Confirmed"
}
export interface backendInterface {
    addToCart(productId: ProductId, quantity: bigint): Promise<void>;
    clearCart(): Promise<void>;
    createProduct(req: CreateProductRequest): Promise<Product>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getAllOrders(): Promise<Array<OrderView>>;
    getAllProducts(): Promise<Array<Product>>;
    getCart(): Promise<Array<CartItemView>>;
    getMyOrders(): Promise<Array<OrderView>>;
    getOrder(orderId: OrderId): Promise<OrderView | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    getProfile(): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    placeOrder(req: PlaceOrderRequest): Promise<OrderView>;
    removeFromCart(productId: ProductId): Promise<void>;
    searchProducts(name: string): Promise<Array<Product>>;
    seedProducts(): Promise<void>;
    setAdminStatus(target: UserId, adminStatus: boolean): Promise<void>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<OrderView | null>;
    updateProduct(id: ProductId, req: CreateProductRequest): Promise<Product | null>;
    updateProfile(req: UpdateProfileRequest): Promise<UserProfile>;
}
import type { Address as _Address, Category as _Category, CreateProductRequest as _CreateProductRequest, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, OrderView as _OrderView, Product as _Product, ProductId as _ProductId, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToCart(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createProduct(arg0: CreateProductRequest): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_CreateProductRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_CreateProductRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<OrderView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItemView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<OrderView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<OrderView> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0);
                return from_candid_OrderView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0);
            return from_candid_OrderView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async setAdminStatus(arg0: UserId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminStatus(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<OrderView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: CreateProductRequest): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_CreateProductRequest_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_CreateProductRequest_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileRequest): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
}
function from_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderView): OrderView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderView]): OrderView | null {
    return value.length === 0 ? null : from_candid_OrderView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    deliveryAddress: _Address;
    deliveryFee: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    estimatedDelivery: _Timestamp;
    totalAmount: bigint;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: Address;
    deliveryFee: bigint;
    userId: UserId;
    createdAt: Timestamp;
    estimatedDelivery: Timestamp;
    totalAmount: bigint;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n12(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        deliveryFee: value.deliveryFee,
        userId: value.userId,
        createdAt: value.createdAt,
        estimatedDelivery: value.estimatedDelivery,
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    inStock: boolean;
    name: string;
    createdAt: _Timestamp;
    description: string;
    category: _Category;
    imageId: string;
    price: bigint;
}): {
    id: ProductId;
    inStock: boolean;
    name: string;
    createdAt: Timestamp;
    description: string;
    category: Category;
    imageId: string;
    price: bigint;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        category: from_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        imageId: value.imageId,
        price: value.price
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InTransit: null;
} | {
    Delivered: null;
} | {
    Confirmed: null;
}): OrderStatus {
    return "InTransit" in value ? OrderStatus.InTransit : "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Meat: null;
} | {
    Beverages: null;
} | {
    Dairy: null;
} | {
    Bakery: null;
} | {
    Household: null;
} | {
    PersonalCare: null;
} | {
    Vegetables: null;
} | {
    Snacks: null;
} | {
    Fruits: null;
}): Category {
    return "Meat" in value ? Category.Meat : "Beverages" in value ? Category.Beverages : "Dairy" in value ? Category.Dairy : "Bakery" in value ? Category.Bakery : "Household" in value ? Category.Household : "PersonalCare" in value ? Category.PersonalCare : "Vegetables" in value ? Category.Vegetables : "Snacks" in value ? Category.Snacks : "Fruits" in value ? Category.Fruits : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderView>): Array<OrderView> {
    return value.map((x)=>from_candid_OrderView_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductRequest): _CreateProductRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: boolean;
    name: string;
    description: string;
    category: Category;
    imageId: string;
    price: bigint;
}): {
    inStock: boolean;
    name: string;
    description: string;
    category: _Category;
    imageId: string;
    price: bigint;
} {
    return {
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        imageId: value.imageId,
        price: value.price
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    InTransit: null;
} | {
    Delivered: null;
} | {
    Confirmed: null;
} {
    return value == OrderStatus.InTransit ? {
        InTransit: null
    } : value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Confirmed ? {
        Confirmed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Meat: null;
} | {
    Beverages: null;
} | {
    Dairy: null;
} | {
    Bakery: null;
} | {
    Household: null;
} | {
    PersonalCare: null;
} | {
    Vegetables: null;
} | {
    Snacks: null;
} | {
    Fruits: null;
} {
    return value == Category.Meat ? {
        Meat: null
    } : value == Category.Beverages ? {
        Beverages: null
    } : value == Category.Dairy ? {
        Dairy: null
    } : value == Category.Bakery ? {
        Bakery: null
    } : value == Category.Household ? {
        Household: null
    } : value == Category.PersonalCare ? {
        PersonalCare: null
    } : value == Category.Vegetables ? {
        Vegetables: null
    } : value == Category.Snacks ? {
        Snacks: null
    } : value == Category.Fruits ? {
        Fruits: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
